### ISSUE TITLE
PotentialSlopeFailure (not responding)

### ISSUE THREAD

**Issue by siriomod** [biglimp/PotentialSlopeFailure#3]
I'm trying to use this plugins considering raster in .tif format. I applied same spatial resolution (30m) and same coordinate system for both raster (DEM; mask 0, 1 cohesive soil).
The study areas is not so extensive however the plugins doesn't finish the elaboration (not responding).

qgis version: Girona
plugin: potential Slope Failure 0.4
machine system: Windows 10; 64-bit

Some suggestions?
thanks

**Comment by biglimp** [comment]
Could you please attach your two raster datasets. /Fredrik

**Comment by siriomod** [comment]
Dear Fredrik,
thanks for your prompt reply,
following the raster dataset
[TEST_QGIS.zip](https://github.com/biglimp/PotentialSlopeFailure/files/1770476/TEST_QGIS.zip)

Sirio

**Comment by biglimp** [comment]
Sorry. I missed this. Looking at your input data it would take days to calculate such huge area. Tile your data if this plugin is to be used.
